# Generated by Django 5.2.4 on 2025-08-19 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_created_at_post_published_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published_at',
            new_name='published_date',
        ),
    ]
